module.exports = {
	"MumbleProto.Version": 0,
	"MumbleProto.UDPTunnel": 1,
	"MumbleProto.Authenticate": 2,
	"MumbleProto.Ping": 3,
	"MumbleProto.Reject": 4,
	"MumbleProto.ServerSync": 5,
	"MumbleProto.ChannelRemove": 6,
	"MumbleProto.ChannelState": 7,
	"MumbleProto.UserRemove": 8,
	"MumbleProto.UserState": 9,
	"MumbleProto.BanList": 10,
	"MumbleProto.TextMessage": 11,
	"MumbleProto.PermissionDenied": 12,
	"MumbleProto.ACL": 13,
	"MumbleProto.QueryUsers": 14,
	"MumbleProto.CryptSetup": 15,
	"MumbleProto.ContextActionModify": 16,
	"MumbleProto.ContextAction": 17,
	"MumbleProto.UserList": 18,
	"MumbleProto.VoiceTarget": 19,
	"MumbleProto.PermissionQuery": 20,
	"MumbleProto.CodecVersion": 21,
	"MumbleProto.UserStats": 22,
	"MumbleProto.RequestBlob": 23,
	"MumbleProto.ServerConfig": 24,
	"MumbleProto.SuggestConfig": 25
}